export const COLOR_PRIMARY = '#FF9C00';
export const COLOR_PRIMARY_OPACY = 'rgba(0, 62, 101, 0.9)';
export const COLOR_SECONDARY = '#000000';
export const COLOR_WHITE = '#f6f6f6';
export const COLOR_GRAY = '#292d3f';//'#686868';
export const COLOR_GRAY_MEDIUM = '#555555';
export const COLOR_GRAY_BORDER = '#fff';
export const COLOR_GRAY_LIGHT = '#f8fafb';
export const COLOR_WHITE_W = '#ffffff';